import { createApp } from 'vue'
import './kioubit-auth-button.js'
import 'mdui/mdui.css'
import 'mdui/components/button.js'
import 'mdui/components/card.js'
import 'mdui/components/chip.js'
import 'mdui/components/circular-progress.js'
import 'mdui/components/dialog.js'
import 'mdui/components/divider.js'
import 'mdui/components/button-icon.js'
import 'mdui/components/icon.js'
import 'mdui/components/list.js'
import 'mdui/components/menu-item.js'
import 'mdui/components/navigation-rail.js'
import 'mdui/components/navigation-rail-item.js'
import 'mdui/components/select.js'
import 'mdui/components/snackbar.js'
import 'mdui/components/switch.js'
import 'mdui/components/tab.js'
import 'mdui/components/tabs.js'
import 'mdui/components/text-field.js'
import './styles.css'
import App from './App.vue'

createApp(App).mount('#app')
